services:
  db:
    image: ghcr.io/cwm360/mariadb:10.5
    env_file: env.ini
    volumes:
      - ./data:/docker-entrypoint-initdb.d:Z
    

  wp:
    #image: ghcr.io/cwm360/wordpress:php8.2-apache
    build:
      context: .
      dockerfile: Containerfile
    env_file: env.ini
    depends_on: 
      - db
    ports:
      - 8000:80
    volumes:
      - ./public_html:/var/www/html:Z

  adminer:
    image: ghcr.io/cwm360/adminer:4.6
    ports:
      - 8181:8080
volumes:
  wpsite: {}

